preferred_syntax = :sass
http_path = '/'
css_dir = '../static/css'
sass_dir = '../static/scss'
images_dir = '../static/img'
javascripts_dir = '../static/js'
relative_assets = true
line_comments = true
# output_style = :compressed